### ISSUE TITLE
osc build -M something does not work with --alternative-project

### ISSUE THREAD

**Issue by bmwiedemann** [openSUSE/osc#376]
Steps To Reproduce:
```bash
osc co openSUSE:Factory/glib2-branding ; cd $_
osc -v -d build --noservice --alternative-project openSUSE:Factory --multibuild-package=openSUSE standard glib2-branding.spec
```

actual result:
```
makeurl: https://api.opensuse.org ['build', 'openSUSE:Factory', 'standard', 'x86_64', '_repository:openSUSE', '_buildinfo'] []
...
The package '_repository:openSUSE' does not exist - please rerun with '--local-package'
```

expected result:
should behave the same as without alternative-project and request
```
makeurl: https://api.opensuse.org ['build', 'openSUSE:Factory', 'standard', 'x86_64', 'glib2-branding:openSUSE', '_buildinfo'] []
```

**Comment by bmwiedemann** [comment]
The _repository:openSUSE is coming form https://github.com/openSUSE/osc/blob/master/osc/build.py#L614
with multibuild portion appended some lines later.

**Comment by marcus-h** [comment]
On 2018-02-06 01:27:17 -0800, Bernhard M. Wiedemann wrote:
> actual result:
> ```
> makeurl: https://api.opensuse.org ['build', 'openSUSE:Factory', 'standard', 'x86_64', '_repository:openSUSE', '_buildinfo'] []
> ...
> The package '_repository:openSUSE' does not exist - please rerun with '--local-package'
> ```
> 
Hmm actually the actual result is the expected result (but probably not
from a user's point of view) :)

> expected result:
> should behave the same as without alternative-project and request
> ```
> makeurl: https://api.opensuse.org ['build', 'openSUSE:Factory', 'standard', 'x86_64', 'glib2-branding:openSUSE', '_buildinfo'] []
> ```
> 
"Fixed" (or changed) in commit 9c4f0d5 ('Ignore
"--alternative-project <prj>" if it is equal to the wc\'s project')

**Comment by bmwiedemann** [comment]
actually, I would like to be able to use --local-package and --alternative-project also with other project names, but that is still broken for multibuild packages - does that need changes on the server side?

**Comment by marcus-h** [comment]
On 2018-02-07 16:19:07 +0000, Bernhard M. Wiedemann wrote:
> actually, I would like to be able to use --local-package and --alternative-project also with other project names, but that is still broken for multibuild packages - does that need changes on the server side?
> 
Ah ok that's what you were hinting at:) I just created a PR [1] for
the corresponding server-side changes.

[1] https://github.com/openSUSE/open-build-service/pull/4461
