### ISSUE TITLE
SIGSEGV on "osc commit"

### ISSUE THREAD

**Issue by z3ntu** [openSUSE/osc#398]
with fish:
```
 /m/h/h/razergenie  osc commit
Sending    _service
Sending    razergenie.dsc
Sending    razergenie.spec
Deleting    razergenie_0.6-1.debian.tar.xz
Deleting    razergenie_0.6.orig.tar.xz
Sending    razergenie_0.7-1.debian.tar.xz
Sending    razergenie_0.7.orig.tar.xz
fish: “osc commit” terminated by signal SIGSEGV (Address boundary error)
```
with bash:
```
[luca@g550jk razergenie]$ osc commit
Log message not specified
a)bort, c)ontinue, e)dit: c
Sending    _service
Sending    razergenie.dsc
Sending    razergenie.spec
Deleting    razergenie_0.6-1.debian.tar.xz
Deleting    razergenie_0.6.orig.tar.xz
Sending    razergenie_0.7-1.debian.tar.xz
Sending    razergenie_0.7.orig.tar.xz
Transmitting file data .....
Committed revision 16.
Waiting for server side source service run
..............double free or corruption (!prev)
Aborted (core dumped)
```
osc version is 0.162.1 and python2 2.7.14-2 (Arch Linux)

sometimes the upload succeeds and the build runs serverside

**Comment by z3ntu** [comment]
gdb backtrace for `/usr/bin/python2 /usr/bin/osc build openSUSE_Leap_42.3 x86_64`: https://pastebin.com/raw/NyLW7icn

**Comment by z3ntu** [comment]
After running this multiple times, I get different results but all end in a crash...
```
 /m/h/h/razergenie  osc commit                                                                                                                                                      Mon 02 Apr 2018 16:04:21 CEST
Sending    razergenie.spec
Transmitting file data .fish: “osc commit” terminated by signal SIGSEGV (Address boundary error)
 !  /m/h/h/razergenie  osc commit                                                                                                                                                  Mon 02 Apr 2018 16:04:31 CEST
Log message not specified
a)bort, c)ontinue, e)dit: c
corrupted double-linked list
fish: “osc commit” terminated by signal SIGABRT (Abort)
 !  /m/h/h/razergenie  osc commit                                                                                                                                                  Mon 02 Apr 2018 16:04:36 CEST
Log message not specified
a)bort, c)ontinue, e)dit: c
Sending    razergenie.spec
fish: “osc commit” terminated by signal SIGSEGV (Address boundary error)
 !  /m/h/h/razergenie  osc commit                                                                                                                                                  Mon 02 Apr 2018 16:04:42 CEST
Log message not specified
a)bort, c)ontinue, e)dit: c
Sending    razergenie.spec
fish: “osc commit” terminated by signal SIGSEGV (Address boundary error)
 !  /m/h/h/razergenie  osc commit                                                                                                                                                  Mon 02 Apr 2018 16:04:47 CEST
Log message not specified
a)bort, c)ontinue, e)dit: c
Sending    razergenie.spec
SSL Error: malloc failure
fish: “osc commit” terminated by signal SIGSEGV (Address boundary error)
 !  /m/h/h/razergenie  osc commit                                                                                                                                                  Mon 02 Apr 2018 16:04:52 CEST
Log message not specified
a)bort, c)ontinue, e)dit: c
Sending    razergenie.spec
Transmitting file data .fish: “osc commit” terminated by signal SIGSEGV (Address boundary error)
 !  /m/h/h/razergenie  osc commit                                                                                                                                                  Mon 02 Apr 2018 16:05:02 CEST
Log message not specified
a)bort, c)ontinue, e)dit: c
Sending    razergenie.spec
fish: “osc commit” terminated by signal SIGSEGV (Address boundary error)
 !  /m/h/h/razergenie  osc commit                                                                                                                                                  Mon 02 Apr 2018 16:05:11 CEST
Log message not specified
a)bort, c)ontinue, e)dit: c
Sending    razergenie.spec
double free or corruption (!prev)
Transmitting file data fish: “osc commit” terminated by signal SIGABRT (Abort)
 !  /m/h/h/razergenie  osc commit                                                                                                                                                  Mon 02 Apr 2018 16:05:14 CEST
Log message not specified
a)bort, c)ontinue, e)dit: c
Sending    razergenie.spec
Transmitting file data .fish: “osc commit” terminated by signal SIGSEGV (Address boundary error)
 !  /m/h/h/razergenie  osc commit                                                                                                                                                  Mon 02 Apr 2018 16:05:19 CEST
Log message not specified
a)bort, c)ontinue, e)dit: c
Sending    razergenie.spec
munmap_chunk(): invalid pointer
Transmitting file data fish: “osc commit” terminated by signal SIGABRT (Abort)
```

**Comment by marcus-h** [comment]
On 2018-04-02 12:56:36 +0000, Luca Weiss wrote:
> gdb backtrace for `/usr/bin/python2 /usr/bin/osc build openSUSE_Leap_42.3 x86_64`: https://pastebin.com/raw/NyLW7icn
> 

> #0  0x00007ffff788352b in _int_malloc () at /usr/lib/libc.so.6
> #1  0x00007ffff7885f6e in calloc () at /usr/lib/libc.so.6
> #2  0x00007fffea59e023 in  () at /usr/lib/libnss_resolve.so.2
> #3  0x00007fffea59e111 in  () at /usr/lib/libnss_resolve.so.2
> #4  0x00007fffea5c073f in  () at /usr/lib/libnss_resolve.so.2
> #5  0x00007fffea5c0b7d in  () at /usr/lib/libnss_resolve.so.2
> #6  0x00007fffea5ada4d in _nss_resolve_gethostbyname4_r () at /usr/lib/libnss_resolve.so.2
> #7  0x00007ffff78e2fd9 in gaih_inet.constprop () at /usr/lib/libc.so.6
> #8  0x00007ffff78e3f04 in getaddrinfo () at /usr/lib/libc.so.6

From a quick glance, this might be an "issue" in libnss_resolve.

How does the backtrace from your second crash look like (the "bash"
case)? It would be interesting to know which lib calls _int_free:

> ..............double free or corruption (!prev)
> Aborted (core dumped)

If it is also caused by libnss_resolve, you could temporarily
disable the lookup via libnss_resolve in /etc/nsswitch.conf
(remove/adapt the "hosts:" line) and check again if osc still
crashes.

**Comment by z3ntu** [comment]
Commenting the `hosts:` line in `/etc/nsswitch.conf` doesn't change anything.
And I can't really give you the coredump of the second example (with the double free) as I have a billion coredumps of python as I have tried it a bunch of times.

Unfortunately because of this issue I can't push anything to OBS :(

**Comment by z3ntu** [comment]
I have managed to get the python3 branch to work with the following patch (@lethliel you could be interested :smiley: )

```diff
--- /usr/lib/python3.6/site-packages/osc/core.py.bak    2018-04-08 11:00:08.000000000 +0200
+++ /usr/lib/python3.6/site-packages/osc/core.py        2018-04-08 11:07:53.151731462 +0200
@@ -4070,7 +4070,7 @@
                 run_external(editor[0], *editor[1:])
         else:
             with open(filename, 'w') as f:
-                f.write(data)
+                f.write(data.decode('UTF-8'))
             orig_mtime = os.stat(filename).st_mtime
             run_editor(filename)
     else:
```
otherwise it would crash with the trace
```
$ osc-py3-wrapper.py commit                                                                                                                  Son 08 Apr 2018 11:01:12 CEST
Traceback (most recent call last):
  File "/usr/bin/osc-py3-wrapper.py", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python3.6/site-packages/osc/babysitter.py", line 61, in run
    return prg.main(argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 344, in main
    return self.cmd(args)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 367, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 501, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 1232, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/python3.6/site-packages/osc/commandline.py", line 4618, in do_commit
    self._commit(subcmd, opts, args)
  File "/usr/lib/python3.6/site-packages/osc/commandline.py", line 4710, in _commit
    msg = get_commit_msg(prj.absdir, pac_objs[prj_path])
  File "/usr/lib/python3.6/site-packages/osc/core.py", line 7248, in get_commit_msg
    msg = edit_message(footer='\n'.join(footer), template=template)
  File "/usr/lib/python3.6/site-packages/osc/core.py", line 4090, in edit_message
    return edit_text(data, delim, suffix='.diff', template=template)
  File "/usr/lib/python3.6/site-packages/osc/core.py", line 4101, in edit_text
    file_changed = _edit_message_open_editor(filename, data, mtime)
  File "/usr/lib/python3.6/site-packages/osc/core.py", line 4073, in _edit_message_open_editor
    f.write(data)
TypeError: write() argument must be str, not bytes
```

**Comment by marcus-h** [comment]
On 2018-04-08 08:46:51 +0000, Luca Weiss wrote:
> Commenting the `hosts:` line in `/etc/nsswitch.conf` doesn't change anything.

Hmm maybe my previous comment was a bit misleading: do not comment the
hosts line out, but maybe replace "resolve" with a different resolver
(e.g., mdns_minimal (if its installed) etc.).

> And I can't really give you the coredump of the second example (with the double free) as I have a billion coredumps of python as I have tried it a bunch of times.
> 
What happens if you directly start osc via gdb?
gdb /usr/bin/python2.7
run /usr/bin/osc build ...

Do you always get the same backtrace?

Do you still get the same backtrace if you run
run /usr/bin/osc commit ...
?

What happens if you run a "pure" local command?
cd <prj>/<pkg>; osc st

Are there osc commands that "seem" to work or do all commands
result in a SIGSEGV?

**Comment by marcus-h** [comment]
On 2018-04-08 03:22:13 -0700, Thaodan wrote:
> Happens also on osc pull
> 
Do you get the same backtrace?
Does the following script also crash?

#!/usr/bin/python
import urllib2

o = urllib2.build_opener()
for _ in range(3):
    f = o.open('https://api.opensuse.org/about')
    print f.read()

**Comment by Thaodan** [comment]
>> Happens also on osc pull
>>
>Do you get the same backtrace?
>Does the following script also crash?
Nope it doesn't crash see here:
https://paste.kde.org/pmdcpkspz

My Backtrace of osc pull is here: 
https://paste.kde.org/p5m2sh2s3

**Comment by Thaodan** [comment]
Python3 doesn't crash too:
https://paste.kde.org/pw3ogqlau

**Comment by marcus-h** [comment]
On 2018-04-08 03:43:56 -0700, Thaodan wrote:
> >> Happens also on osc pull
> >>
> >Do you get the same backtrace?
> >Does the following script also crash?
> Nope it doesn't crash see here:
> https://paste.kde.org/pmdcpkspz
> 
> My Backtrace of osc pull is here: 
> https://paste.kde.org/p5m2sh2s3
> 
Great! (btw., it is "osc up" not "osc pull").

Does the following script work for you? (that is, not
resulting in a SIGSEGV)

from M2Crypto import m2urllib2

def _req():
    for _ in range(3):
        f = o.open('https://api.opensuse.org/about')
        print f.read()


o = m2urllib2.build_opener()
for _ in range(5):
    _req()


Just for testing: you could also temporarily disable the
ssl cert check (that is, "disabling" m2crypto) and check
if it still crashes:

osc config https://api.opensuse.org sslcertck 0

(assuming that you are using api.o.o) To enable it again:
- osc config https://api.opensuse.org sslcertck 1, or
- make a backup of the old config and restore it


Which distribution are you using?

**Comment by Thaodan** [comment]
>Great! (btw., it is "osc up" not "osc pull").
Sorry, thats the habbit of using git.

>Does the following script work for you? (that is, not
>resulting in a SIGSEGV)
Yes it doees.



>Just for testing: you could also temporarily disable the
>Ssl cert check (that is, "disabling" m2crypto) and check
>if it still crashes:
Nope it doesn't, works.

>Which distribution are you using?
Arch Linux, x86_64

I'm the maintainer of the aur pkg of osc.

**Comment by lethliel** [comment]
On 04/08/2018 11:08 AM, Luca Weiss wrote:
> I have managed to get the python3 branch to work with the following patch (@lethliel <https://github.com/lethliel> you could be interested 😃 )

Thanks. I don't even thought about the possibility that someone could use an editor other than vim :-)
I fixed it with commit https://github.com/openSUSE/osc/commit/4ee2e34d5fc4d8ca34a10feb2fd4b88131f12e86

Thanks for the catch.

**Comment by Thaodan** [comment]
>> I have managed to get the python3 branch to work with the following patch 
(@lethliel <https://github.com/lethliel> you could be interested 😃 )

>Thanks. I don't even thought about the possibility that someone could use an 
editor other than vim :-)
This another issue or not?
Don't know why the editor would make a change.

**Comment by lethliel** [comment]
Yes. This is another issue. Just wanted to answer @z3ntu here. (because there was no separate issue for this). Sorry for hijacking this conversation.

**Comment by z3ntu** [comment]
@lethliel $EDITOR is nvim, so neovim :wink: 

@Thaodan this is about the python3 branch that I have tried and makes osc work for me. It's still an issue with the master branch and python 2 though.

**Comment by marcus-h** [comment]
On 2018-04-08 11:26:58 +0000, Thaodan wrote:
> >Just for testing: you could also temporarily disable the
> >Ssl cert check (that is, "disabling" m2crypto) and check
> >if it still crashes:
> Nope it doesn't, works.
> 
Ok, good.

> >Which distribution are you using?
> Arch Linux, x86_64
> 
I can finally reproduce it with openSUSE Tumbleweed and with
an Arch VM (though, I had to slightly modify the python2-M2Crypto
code in both cases (0.29.0)...)
Now, the interesting question is which python2-M2Crypto version are
you using?

(Just for the record: from a quick glance this is a bug in osc).

> I'm the maintainer of the aur pkg of osc.
> 
Thanks for taking care of osc in Arch! Much appreciated!

**Comment by marcus-h** [comment]
Just to be sure I'm seeing the same thing as you (a bug in osc
wrt. to the session handling (somewhat similar to [1]))

Which

- python-M2Crypto
- libopenssl

versions are you using?

(from my observation it started to "break" with libopenssl1_1
(libopenssl1_0_0 "seem" to work)... I'll work out the details
in the next days/end of the week)

[1] https://bugzilla.suse.com/show_bug.cgi?id=1068470#c45

**Comment by Thaodan** [comment]
Sorry for the delay:
Name                     : openssl
Version                  : 1.1.0.h-1

Name                     : python2-m2crypto
Version                  : 0.29.0-1

**Comment by pfactum** [comment]
For me it segfaults on different commands (up, ci etc) with m2crypto v0.28 and v0.30 (the latest one ATM), but not with v0.29. Also, if I recompile m2crypto against openssl-1.0, it works too even with v0.30.

**Comment by marcus-h** [comment]
"Fixed" (aka disabled session resumption) in commit b730f88 ("Disable
ssl session resumption"). I need to think about how to reliably
implement session resumption...

Anyway, thanks for your reports!

**Comment by Thaodan** [comment]
I applied the patch to the last released version, but still get an error on commit:
```
~/dev/sailfish/pkgs/home:Thaodan:testing:packagekit/:osc commit 
Waiting for Emacs...
nothing to do for package harbour-storeman
Deleting    PackageKit
Deleting    PackageKit-Qt5
double free or corruption (!prev)
zsh: abort (core dumped)  osc commit

``
Patch not working or is it not working with the way I did it?

**Comment by Thaodan** [comment]
Coredump:
```
                Stack trace of thread 21623:
                #0  0x000014ee770f2efb raise (libc.so.6)
                #1  0x000014ee770f42c1 abort (libc.so.6)
                #2  0x000014ee771359d7 __libc_message (libc.so.6)
                #3  0x000014ee7713bfda malloc_printerr (libc.so.6)
                #4  0x000014ee7713da9c _int_free (libc.so.6)
                #5  0x000014ee73d00d9d SSL_SESSION_free (libssl.so.1.1)
                #6  0x000014ee73cfcf3c SSL_free (libssl.so.1.1)
                #7  0x000014ee6e318423 n/a (_m2crypto.so)
                #8  0x000014ee76d26e29 PyEval_EvalFrameEx (libpython2.7.so.1.0)
                #9  0x000014ee76dc05a6 PyEval_EvalCodeEx (libpython2.7.so.1.0)
                #10 0x000014ee76d67bcf function_call.lto_priv.221 (libpython2.7.so.1.0)
                #11 0x000014ee76d14003 PyObject_Call (libpython2.7.so.1.0)
                #12 0x000014ee76d9351f instancemethod_call.lto_priv.136 (libpython2.7.so.1.0)
                #13 0x000014ee76d14003 PyObject_Call (libpython2.7.so.1.0)
                #14 0x000014ee76dbfccf PyEval_CallObjectWithKeywords (libpython2.7.so.1.0)
                #15 0x000014ee76dd4945 slot_tp_del (libpython2.7.so.1.0)
                #16 0x000014ee76d88585 subtype_dealloc (libpython2.7.so.1.0)
                #17 0x000014ee76d7fbce PyMember_SetOne (libpython2.7.so.1.0)
                #18 0x000014ee76d3beca _PyObject_GenericSetAttrWithDict (libpython2.7.so.1.0)
                #19 0x000014ee76d3c3b6 PyObject_SetAttr (libpython2.7.so.1.0)
                #20 0x000014ee76d28044 PyEval_EvalFrameEx (libpython2.7.so.1.0)
                #21 0x000014ee76d27550 PyEval_EvalFrameEx (libpython2.7.so.1.0)
                #22 0x000014ee76dc05a6 PyEval_EvalCodeEx (libpython2.7.so.1.0)
                #23 0x000014ee76d67bcf function_call.lto_priv.221 (libpython2.7.so.1.0)
                #24 0x000014ee76d14003 PyObject_Call (libpython2.7.so.1.0)
                #25 0x000014ee76d9351f instancemethod_call.lto_priv.136 (libpython2.7.so.1.0)
                #26 0x000014ee76d14003 PyObject_Call (libpython2.7.so.1.0)
                #27 0x000014ee76dbfccf PyEval_CallObjectWithKeywords (libpython2.7.so.1.0)
                #28 0x000014ee76dd4945 slot_tp_del (libpython2.7.so.1.0)
                #29 0x000014ee76d88585 subtype_dealloc (libpython2.7.so.1.0)
                #30 0x000014ee76d42b80 PyDict_Clear (libpython2.7.so.1.0)
                #31 0x000014ee76d3fbda dict_tp_clear.lto_priv.266 (libpython2.7.so.1.0)
                #32 0x000014ee76d5a00b collect.lto_priv.1144 (libpython2.7.so.1.0)
                #33 0x000014ee76ddf251 PyGC_Collect (libpython2.7.so.1.0)
                #34 0x000014ee76ddda85 Py_Finalize (libpython2.7.so.1.0)
                #35 0x000014ee76dddb89 Py_Exit (libpython2.7.so.1.0)
                #36 0x000014ee76dddcaa handle_system_exit (libpython2.7.so.1.0)
                #37 0x000014ee76dddd07 PyErr_PrintEx (libpython2.7.so.1.0)
                #38 0x000014ee76ce8083 PyRun_SimpleFileExFlags.cold.68 (libpython2.7.so.1.0)
                #39 0x000014ee76dd28d3 Py_Main (libpython2.7.so.1.0)
                #40 0x000014ee770df9a7 __libc_start_main (libc.so.6)
                #41 0x000055d668d4b77a _start (python2.7)
```

**Comment by lazka** [comment]
b730f88 fixes the crash for me on Debian sid.

**Comment by marcus-h** [comment]
On 2018-05-13 15:32:48 -0700, Thaodan wrote:
> I applied the patch to the last released version, but still get an error on commit:
> ```
> ~/dev/sailfish/pkgs/home:Thaodan:testing:packagekit/:osc commit 
> Waiting for Emacs...
> nothing to do for package harbour-storeman
> Deleting    PackageKit
> Deleting    PackageKit-Qt5
> double free or corruption (!prev)
> zsh: abort (core dumped)  osc commit
> 
> ``
> Patch not working or is it not working with the way I did it?
> 
Hmm I've no clue how you applied the patch:) In doubt, just upload the
patched code. Since Arch is a rolling distro, which python2-m2crypto,
libopenssl, and python2 versions are you using?

>                 #33 0x000014ee76ddf251 PyGC_Collect (libpython2.7.so.1.0)
>                 #34 0x000014ee76ddda85 Py_Finalize (libpython2.7.so.1.0)
>                 #35 0x000014ee76dddb89 Py_Exit (libpython2.7.so.1.0)
>                 #36 0x000014ee76dddcaa handle_system_exit (libpython2.7.so.1.0)
>                 #37 0x000014ee76dddd07 PyErr_PrintEx (libpython2.7.so.1.0)
>                 #38 0x000014ee76ce8083 PyRun_SimpleFileExFlags.cold.68 (libpython2.7.so.1.0)
>                 #39 0x000014ee76dd28d3 Py_Main (libpython2.7.so.1.0)
>                 #40 0x000014ee770df9a7 __libc_start_main (libc.so.6)
>                 #41 0x000055d668d4b77a _start (python2.7)
> 
Hmm with the patch applied, the trace is slightly different (now, it
crashes when handling a SystemExit exception), but this might be just
a coincidence... Is this crash "reproducable"?

**Comment by marcus-h** [comment]
On 2018-05-14 17:42:25 +0200, Marcus Hüwe wrote:
> On 2018-05-13 15:32:48 -0700, Thaodan wrote:
> > I applied the patch to the last released version, but still get an error on commit:
> > ```
> > ~/dev/sailfish/pkgs/home:Thaodan:testing:packagekit/:osc commit 
> > Waiting for Emacs...
> > nothing to do for package harbour-storeman
> > Deleting    PackageKit
> > Deleting    PackageKit-Qt5
> > double free or corruption (!prev)
> > zsh: abort (core dumped)  osc commit
> > 
> > ``
> > Patch not working or is it not working with the way I did it?
> > 
> Hmm I've no clue how you applied the patch:) In doubt, just upload the
> patched code. Since Arch is a rolling distro, which python2-m2crypto,
> libopenssl, and python2 versions are you using?
> 
I just set up an Arch VM (basically, just a
- cd openSUSE:Tools/osc
- osc build Arch -x linux -x vim -x gdb -x strace -x dhcpcd -x python2 \
    -x iputils -x iproute2 -x systemd
- patch osc code in the VM
) and ran "osc co Base:System", which seems to work (manually aborted
after 133 packages).
Can you check, if you correctly applied the patch?

**Comment by Thaodan** [comment]
yes I had. See here:
https://aur.archlinux.org/packages/osc/

Did you try osc commit?


pkg versions:
Name                     : openssl
Version                  : 1.1.0.h-1
Name                     : python2
Version                  : 2.7.15-1
Name                     : python2-m2crypto
Version                  : 0.30.1-1

**Comment by pfactum** [comment]
FWIW, the commit has worked for me so far.

**Comment by Thaodan** [comment]
did you use the aur pkg or the latest -git?

**Comment by marcus-h** [comment]
Sorry for the late reply...

On 2018-05-13 15:32:48 -0700, Thaodan wrote:
> Patch not working or is it not working with the way I did it?
> 
Can you try to reproduce it in a "clean" environment? Let's try it
via KVM as follows:

- backup your ~/.oscrc or ~/.config/osc/oscrc file and remove the
  config file (so that we can start with a fresh osc config)

- let's export some env vars so that we don't have to hardcode the
  paths in the following commands:

  # where to store vm related files (e.g. images)
  export VM_BASE=/srv/vm
  # where to store the vm images
  export VM_ROOT="$VM_BASE/root"

- checkout osc sources and prepare them:
  osc co openSUSE:Tools/osc
  cd openSUSE:Tools/osc
  sed -i "s/ 'urlgrabber'//" PKGBUILD

- prepare osc for a kvm build:
  osc config general build-root $VM_ROOT
  osc config general build-type kvm
  osc config general build-vmdisk-rootsize 5000
  osc config general build-vmdisk-swapsize 2000

- start the build:
  osc build Arch x86_64 PKGBUILD \
    -x gdb -x systemd -x python2-m2crypto \
    -x vim -x dhcpcd -x iproute2 -x linux \
    -x ca-certificates -x git

  (the build will fail due to a missing urlgrabber dependency)

- set a root password and copy kernel+initrd:
  su
  mount $VM_ROOT/img /mnt
  cp /mnt/boot/vmlinuz-linux $VM_BASE/
  cp /mnt/boot/initramfs-linux.img $VM_BASE/
  chroot /mnt
  passwd
  exit
  umount /mnt

- start the vm (the command is on a single line):
  /usr/bin/qemu-kvm -nodefaults -no-reboot -nographic -net nic -net user -runas qemu -cpu host -kernel $VM_BASE/vmlinuz-linux -initrd $VM_BASE/initramfs-linux.img -append "root=/dev/sda init=/usr/lib/systemd/systemd rootfstype=ext3 rootflags=data=writeback,nobarrier,commit=150,noatime panic=1 no-kvmclock nmi_watchdog=0 rw rd.driver.pre=binfmt_misc elevator=noop console=ttyS0" -drive file=$VM_ROOT/img,format=raw,if=none,id=disk,serial=0,cache=unsafe -device ide-hd,drive=disk -drive file=$VM_ROOT/swap,format=raw,if=none,id=swap,serial=1,cache=unsafe -device ide-hd,drive=swap -serial mon:stdio -smp 2

- login as root and setup the network (in the vm):
  dhcpcd ens2

- switch to the abuild user and clone the osc git repo (in the vm):
  su - abuild
  git clone https://github.com/openSUSE/osc.git

- add an urlgrabber workaround to the osc code and checkout a somewhat
  "larger" project (in the vm):
  sed -i /URLGrabError/d osc/osc/babysitter.py
  export PYTHONPATH=$PWD/osc
  python2 osc/osc-wrapper.py co Base:System


Does this also result in a segfault?

**Comment by marcus-h** [comment]
On 2018-05-31 15:42:52 +0200, Marcus Hüwe wrote:
> On 2018-05-13 15:32:48 -0700, Thaodan wrote:
> > Patch not working or is it not working with the way I did it?
> > 
> Can you try to reproduce it in a "clean" environment? Let's try it
> via KVM as follows:
> 
(Of course, you need a working osc on your host machine (IIUC, it works
for you if you disable the sslcert check:
osc config https://api.opensuse.org sslcertk 0
(NOTE: this is insecure:/) )
